# Generated by Django 2.2.3 on 2019-11-01 18:53

import django.core.validators
from django.db import migrations, models
import ieeewebsite.apps.team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField(default=1, help_text='Serial Number Of Member Display')),
                ('Member_Name', models.CharField(help_text='Name Of the Team Member', max_length=30)),
                ('Member_Post', models.CharField(help_text='Position Of the Team Member', max_length=30)),
                ('Display_img', models.ImageField(blank=True, help_text='Display image of the Team member', null=True, upload_to='uploads/team/images/members')),
                ('Session_start', models.IntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2015), ieeewebsite.apps.team.models.max_value_current_year])),
                ('Session_end', models.IntegerField(default=models.IntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2015), ieeewebsite.apps.team.models.max_value_current_year]))),
            ],
        ),
    ]
