# Generated by Django 2.2.3 on 2019-12-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Display_img',
            field=models.ImageField(blank=True, help_text='Display image of the Team member', null=True, upload_to='team/members'),
        ),
    ]
