# Generated by Django 3.0.6 on 2020-08-12 17:33

import django.core.validators
from django.db import migrations, models
import ieeewebsite.apps.team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20191225_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Session_end',
            field=models.IntegerField(default=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2015), ieeewebsite.apps.team.models.max_value_current_year])),
        ),
        migrations.AlterField(
            model_name='team',
            name='Session_start',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2015), ieeewebsite.apps.team.models.max_value_current_year]),
        ),
    ]
