# Generated by Django 2.2.3 on 2019-11-01 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(help_text='Name Of the Event', max_length=30)),
                ('Discription', models.CharField(blank=True, help_text='Small description about the Event', max_length=500, null=True)),
                ('Event_Date', models.DateField(default=datetime.date(2019, 11, 2))),
                ('Event_Time', models.TimeField()),
                ('Details', models.CharField(blank=True, help_text='Details about the Event', max_length=500, null=True)),
                ('Event_status', models.CharField(choices=[('CMP', 'Completed'), ('ONG', 'Ongoing'), ('UPC', 'Upcoming')], default='Completed', help_text='Status of the Event', max_length=3)),
                ('Display_img', models.ImageField(blank=True, help_text='Cover Image Of the event', null=True, upload_to='uploads/events/images/CoverImage')),
            ],
        ),
    ]
