# Generated by Django 3.0.6 on 2020-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200812_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_Subheading',
        ),
        migrations.AddField(
            model_name='event',
            name='Event_Heading',
            field=models.CharField(default='IEEE', help_text='Heading Of the Event. Default = IEEE', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_Name',
            field=models.CharField(help_text='Name Of the Event (Sub Heading', max_length=30),
        ),
    ]
