# Generated by Django 3.0.6 on 2020-08-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_slides',
            name='Display_img',
            field=models.ImageField(default='home/images/cover_photo/IEEE_cover1.jpg', help_text='Cover Image Of the event', upload_to='home/images/cover_photo'),
        ),
    ]
